#!/usr/bin/perl

use strict;
use warnings;
use PVE::QemuServer;
use PVE::Tools qw(run_command);
use PVE::Network;
use PVE::Database;

my $iface = shift;

die "no interface specified\n" if !$iface;

die "got strange interface name '$iface'\n" 
    if $iface !~ m/^tap(\d+)i(\d+)$/;

my $vmid = $1;
my $netid = "net$2";

my $migratedfrom = $ENV{PVE_MIGRATED_FROM};

my $conf = PVE::QemuServer::load_config($vmid, $migratedfrom);

die "unable to get network config '$netid'\n"
    if !$conf->{$netid};

my $net = PVE::QemuServer::parse_net($conf->{$netid});
die "unable to parse network config '$netid'\n" if !$net;

my $vmdbconf = PVE::Database::load_vmdb_conf($vmid);

my $rate = $vmdbconf->{network}->{rate};
$rate = $vmdbconf->{network}->{exceededrate} if($vmdbconf->{network}->{netlock} eq 1 && $vmdbconf->{network}->{exceededrate});

PVE::Network::tap_create($iface, $net->{bridge});

PVE::Network::tap_rate_limit($iface, $rate) if $rate;

PVE::Network::tap_plug($iface, $net->{bridge}, $net->{tag}, $net->{firewall});

exit 0;
